### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by jterry64** [gfw-api/gfw-raster-analysis-lambda#17]
Ticket just to keep track of results from performance testing. AWS XRay is now configured, and thoughts from a few initial tests:

- S3 reads are the biggest bottlenecks and are proportional to size of data in window. Currently changing to do all reads in parallel, but may also considering encoding multiple rasters commonly use rasters into one. 
- S3 reads are significantly faster on the second time. I'm curious if this is just for the section of the tile read, or reading anywhere from the tile will be faster the more you do it (that would have great performance implications for the full datacube algorithm).
- Running on 5 MHa area with 3 rasters hit the memory limits, so might need to be run on smaller areas than we though. The code is duplicating the data at a few points, so reducing that could get us larger areas (or if there's a way to force Python to release the memory at each stage?)
- The pandas aggregation does actually take a significant amount of time for large areas, on the same scale as each S3 read. We can see what possibilities there are for speeding that up.

**Comment by thomas-maschler** [comment]
A couple of thoughts:

**S3 handshake**
Repeated s3 reads could be faster due to an already established HTTP connection. You save the time to establish the handshake.

In nodeJS you can set a [global variable](https://aws.amazon.com/blogs/networking-and-content-delivery/leveraging-external-data-in-lambdaedge/) to keep the HTTP Connection alive across multiple lambda invocations. I haven't found an equivalent option for boto3, yet.

General recommendations I found is to place the initialization of the S3 client [outside of the function handler](https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html) for later reuse in the same instance:
_Initialize SDK clients and database connections outside of the function handler, and cache static assets locally in the /tmp directory. Subsequent invocations processed by the same instance of your function can reuse these resources. This saves execution time and cost_

On the other hand, connections don't seem to be [thread safe](https://github.com/boto/boto3/issues/828). Recommendation here seem to conflict with best practices above.

You can set parameters of your [configuration file to keep connections alive](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html?highlight=tcp_keepalive#configuration-file) but this won't work in a lambda context.


**Release memory**
To release an numpy array from memory you simply set the variable to `None`. You should do that immediately after the last time you used it. Also make sure you alway use the smallest [data type](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html) possible when reading an array to reduce memory consumption to begin with 

**Pandas**
Sounds like we need to find the sweet spot between 
- time to invoke one or multiple lambda functions
- time to read data
- time to process data
How long does it take to process the same area with just one invocation vs multiple parallel invocations and then aggregating final results

**Comment by jterry64** [comment]
re: release memory, there's actual a `del` keyword that just unbinds the variable. But both those just dereference it, Python still has the memory allocated until it garbage collects. I'm unsure if garbage collection would always happen before we start allocating more memory for other objects. However, I found Python actually has a garbage collection API you can use to force collection, so I can use that if it's necessary.

re: S3 handshake, I don't think the faster repeated reads are because of the handshake time, because this was observed between different lambda invocations so the connection would've been taken down between each. It also seems read time is mostly proportional to data size, so the handshake might be less significant for our time scale (vs. a function doing lots of small transactions). But I can measure how long that's adding to the read each time.

**Comment by jterry64** [comment]
After some memory profiling, it turns out the memory issue the function is hitting is actually from pandas: it seems like the pandas groupby function allocates a ton of temporary memory.  On a 5 MHa geometry, the total memory allocated for the reading the rasters was ~1.5 GB. 

I used resource.getrusage, which lets you see the peak memory usage during the application, before and after pandas groupby, and the peak had hit over 4.5 GB! I think pandas deallocates the memory as it goes, but Python doesn't automatically give released memory back to the OS (it keeps it around for future Python objects), so from the perspective of Lambda we're hitting the limit. I found other people on stack overflow who ran into this issue, but no good solution really. So maybe it'd be better to go back to using NumPy so we can control the memory allocation.

**Comment by jterry64** [comment]
Start doing performance testing on calling this lambda functions concurrently across a geometry. Created a simple lambda function (raster-analysis-perf-tester) that takes a geometry and zoom level and uses mercantile to break it apart into tiled geometries. Then invoke the raster analysis lambda function on each.

Quite a few interesting things came out of this, but most important few:

- There's definitely a bit of overhead: the invoke call takes some time, then it sits in a queue ("dwell time"), then lambda might have to initialize a new container for each since it can't reuse containers concurrently. This can add 1-4 seconds, so on smaller geometries (< 5MHa) it can be slower than just calling the analysis function on the entire geometry.
- With that said, it scales incredibly well. Once you get past the startup cost, the lambda functions run essentially in parallel, and so the time ends up being about overhead + <analysis function run at zoom level> (bottleneck is usually zoom tiles with long s3 reads, possibly because just more dense data, especially from tcd). I ran this on a 100 MHa geometry at zoom level 7, and takes 10 seconds for the whole thing to complete. That already seems to outperform GEE and other options listed on the Azavea report, before using datacube precomputation. (although not currently doing any collection/aggregation, which probably add a few seconds)
-Definitely some kinks we'll need to work with running many lambda functions concurrently; once I started running over 100, I'd sometimes get really random hang ups. Sometimes with lambda functions seemingly stuck on the queue, other times seemed like issues with too many concurrent reads on a tile in s3 (seemed like some reads were getting locked for awhile).

**Comment by thomas-maschler** [comment]
Very interesting!
lambda warm up period is certainly something to consider
here is an interesting article on how to keep multipe containers of the same function warm
https://medium.com/thundra/dealing-with-cold-starts-in-aws-lambda-a5e3aa8f532

If it adds to the response time we might be able to replicate something similar using some scheduled warm up calls with cloud watch

**Comment by jterry64** [comment]
Most optimizations complete and tested
